- name: Install glance
  yum:
    name: openstack-glance

- name: Prerequisites Database
  include: mysql.yml

- name: Copy glance.conf
  include: config.yml

- name: Restart the Glance service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - glance-registry.service
    - glance-api.service
