---
- hosts: controller
  become: yes
  roles:
    - { role: common/hostname }
    - { role: chrony }
    - { role: package }
    - { role: mariadb/mariadb-single }
    - { role: rabbitmq/single }
    - { role: memcached }
    - { role: etcd }
    - { role: keystone/single }
    - { role: glance/single }
    - { role: nova/controller/single }
    - { role: neutron/controller/single }
    - { role: horizon }
    - { role: cinder/controller/single }
    - { role: heat/single }
    - { role: aodh/single }
    - { role: gnocchi/single }
    - { role: ceilometer/controller }
    - { role: docker }
    - { role: grafana }

- hosts: compute
  become: yes
  roles:
    - { role: common/hostname }
    - { role: chrony }
    - { role: package }
    - { role: nova/compute}
    - { role: neutron/compute }
    - { role: ceilometer/compute }

- hosts: storage
  become: yes
  roles:
    - { role: common/hostname }
    - { role: chrony }
    - { role: package }
    - { role: cinder/storage }
