- name: Install Neutron
  yum:
    name: "{{ item }}"
  with_items:
    - openstack-neutron 
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - openstack-neutron-lbaas
    - ebtables

- name: Copy neuton.conf
  include: config.yml

- name: Prerequisites Database
  include: mysql.yml

- name: Restart the Neutron service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - neutron-server.service
    - neutron-linuxbridge-agent.service
    - neutron-dhcp-agent.service
    - neutron-metadata-agent.service
    - neutron-l3-agent.service
    - neutron-lbaasv2-agent.service

- name: Restart the Nova API service
  systemd:
    name: openstack-nova-api.service
    state: restarted
