- name: Install neutron-server
  apt:
    name: "{{ item }}"
  with_items:
    - neutron-server 
#    - neutron-plugin-ml2
#    - neutron-linuxbridge-agent 
#    - neutron-l3-agent 
#    - neutron-dhcp-agent
#    - neutron-metadata-agent

- name: Copy neutron.conf
  include: config.yml

- name: Prerequisites Database
  include: mysql.yml
  run_once: true

- name: Restart the Neutron-server service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - neutron-server 
#    - neutron-linuxbridge-agent 
#    - neutron-l3-agent 
#    - neutron-dhcp-agent
#    - neutron-metadata-agent
    - nova-api
