- name: Enabling the yum Repository
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum/repos.d/MariaDB.repo

- name: Install python-pymysql
  yum:
    name: "{{ item }}"
  with_items:
    - MariaDB-client
    - MariaDB-Galera-server
    - galera
    - python2-PyMySQL

- name : Configure mariadb
  include: config.yml

- name: Restart mysql service
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

