- name: Set root Password
  mysql_user: 
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes 
    name: root
    login_user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
