- name: Copy 99-openstack.cnf to /etc/mysql/mariadb.conf.d/
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy 99-openstack.cnf to /etc/mysql/mariadb.conf.d/
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/my.cnf.d/openstack.cnf
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
