- name: Create heat user
  command: openstack {{ keystone_auth }} user create --domain default --password {{ heat_user_password }} heat

- name: Create admin role to the heat user and service project
  command: openstack {{ keystone_auth }} role add --project service --user heat admin

- name: Create heat service
  command: openstack {{ keystone_auth }} service create --name heat --description "Orchestration" orchestration

- name: Create heat cloudformation service
  command: openstack {{ keystone_auth }} service create --name heat-cfn --description "Orchestration" cloudformation

- name: Create heat API endpoint
  command: openstack {{ keystone_auth }} endpoint create --region RegionOne orchestration "{{ item }}" http://{{ openstack_vip_address }}:8004/v1/%\(tenant_id\)s
  with_items:
    - public
    - internal
    - admin

- name: Create heat cloudformation API endpoint
  command: openstack {{ keystone_auth }} endpoint create --region RegionOne cloudformation "{{ item }}" http://{{ openstack_vip_address }}:8000/v1
  with_items:
    - public
    - internal
    - admin

- name: Create the heat domain that contains projects and users for stacks
  command: openstack {{ keystone_auth }} domain create --description "Stack projects and users" heat

- name: Create the heat_domain_admin user to manage projects and users in the heat domain
  command: openstack {{ keystone_auth }} user create --domain heat --password {{ heat_user_password }} heat_domain_admin

- name: Add the admin role to the heat_domain_admin user in the heat domain
  command: openstack {{ keystone_auth }} role add --domain heat --user-domain heat --user heat_domain_admin admin

- name: Create the heat_stack_owner role
  command: openstack {{ keystone_auth }} role create heat_stack_owner

- name: Create the heat_stack_user role
  command: openstack {{ keystone_auth }} role create heat_stack_user
