- name: Create the glance database
  mysql_db:
    login_user: root
    name: glance
    state: present

- name: Grant proper access to the glance database
  mysql_user:
    name: glance
    password: "{{ glance_db_password }}"
    priv: "glance.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"

- name: Populate the Image service database
  shell: glance-manage db_sync
  args:
    executable: /bin/sh
