- name: Copy 99-openstack.cnf to /etc/mysql/mariadb.conf.d/
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/my.cnf.d/openstack.cnf

- name: Restart mysql service
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

