- name: Install aodh
  yum:
    name: "{{ item }}"
  with_items:
    - openstack-aodh-api
    - openstack-aodh-evaluator
    - openstack-aodh-notifier
    - openstack-aodh-listener
    - openstack-aodh-expirer
    - python-aodhclient

- name: Copy glance.conf
  include: config.yml

- name: Prerequisites Database
  include: mysql.yml

- name: Restart the Alarm service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - openstack-aodh-api.service
    - openstack-aodh-evaluator.service
    - openstack-aodh-notifier.service
    - openstack-aodh-listener.service
