- name: Install nova
  apt:
    name: "{{ item }}"
  with_items:
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy 
    - nova-scheduler 
    - nova-placement-api

- name: Copy nova.conf
  include: config.yml

- name: Prerequisites Database
  include: mysql.yml
  when: inventory_hostname == groups['controller'][0]

- name: Restart the Nova service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy 
    - nova-scheduler 
