- name: Configure AppArmor to work with Galera Cluster
  file:
    src: /etc/apparmor.d/usr.sbin.mysqld
    dest: /etc/apparmor.d/disable/usr.sbin.mysqld
    state: link

- name: Restart AppArmor
  systemd:
    name: apparmor
    state: restarted
