- name: Install chrony
  apt:
    name: chrony
    update_cache: yes

- name: Copy chrony.conf to /etc/chrony/
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf

- name: Restart chrony service
  service:
    name: chrony
    state: restarted
