- name: Create neutron user
  command: openstack {{ keystone_auth }} user create --domain default --password {{ neutron_user_password }} neutron

- name: Create admin role to the neutron user and service project
  command: openstack {{ keystone_auth }} role add --project service --user neutron admin

- name: Create neutron service
  command: openstack {{ keystone_auth }} service create --name neutron --description "OpenStack Networking" network

- name: Create neutron API endpoint
  command: openstack {{ keystone_auth }} endpoint create --region RegionOne network "{{ item }}" http://{{ openstack_vip_address }}:9696
  with_items:
    - public
    - internal
    - admin
