- name: Install heat
  yum:
    name: "{{ item }}"
  with_items:
    - openstack-heat-api 
    - openstack-heat-api-cfn
    - openstack-heat-engine

- name: Prerequisites Database
  include: mysql.yml

- name: Copy glance.conf
  include: config.yml

- name: Restart the Orchestration service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - openstack-heat-api 
    - openstack-heat-api-cfn
    - openstack-heat-engine
