- name: Install heat 
  apt:
    name: "{{ item }}"
  with_items:
    - heat-api 
    - heat-api-cfn 
    - heat-engine

- name: Copy glance.conf
  include: config.yml

- name: Prerequisites Database
  include: mysql.yml
  when: inventory_hostname == groups['controller'][0]


- name: Restart the Orchestration service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - heat-api 
    - heat-api-cfn 
    - heat-engine
