#- name: Install collectd
#  apt:
#    name: "{{ item }}"
#  with_items:
#    - collectd
#    - python-pip

#- name: Install collectd-gnocchi
#  pip:
#    name: collectd-gnocchi

#- name: Create gnocchi policy
#  command: "{{ item }}" 
#  with_items:
#    - gnocchi {{ keystone_auth_url }} {{ project_domain_name }} {{ user_domain_name }} {{ project_name }} {{ username }} {{ password }} --os-auth-type password archive-policy create -d granularity:0:05:00,points:8640 rate:low -m rate:last
#    - gnocchi {{ keystone_auth_url }} {{ project_domain_name }} {{ user_domain_name }} {{ project_name }} {{ username }} {{ password }} --os-auth-type password archive-policy-rule create -m "interface-*@if_*" -a rate:low network-interface-rate
#  when: inventory_hostname == groups['controller'][0]

#- name: Restart collectd
#  service:
#    name: collectd
#    state: restarted
