- name: Create the cinder database
  mysql_db:
    login_user: root
    name: cinder
    state: present

- name: Grant proper access to the cinder database
  mysql_user:
    name: cinder
    password: "{{ cinder_db_password }}"
    priv: "cinder.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"

- name: Populate the Image service database
  shell: cinder-manage db sync
  args:
    executable: /bin/sh
