- name: Install nova-compute
  yum:
    name: openstack-nova-compute

- name: Copy nova.conf
  include: config.yml

- name: Start the Nova Compute service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - libvirtd.service
    - openstack-nova-compute.service
