- name: Copy nova.conf to /etc/nova/
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf

- name: Check Compute node does not support hardware acceleration
  command: >
    egrep -c '(vmx|svm)' /proc/cpuinfo
  failed_when: result.rc != 1
  register: result

- name: Edit /etc/nova/nova-compute.conf
  lineinfile:
    dest: /etc/nova/nova-compute.conf 
    state: present
    regexp: '^virt_type=kvm'
    line: 'virt_type=qemu'
  when: result.stdout == '0'
