- name: Install memcache
  apt:
    name: "{{ item }}"
  with_items:
    - memcached
    - python-memcache

- name: Copy memcached.conf to /etc/
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf

- name: Restart Memcached service
  service:
    name: memcached
    state: restarted


