- name: Copy keystone.conf to /etc/keystone/
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf

- name: Ubuntu Configure the Apache HTTP server
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: "ServerName {{ openstack_vip_address }}"
    state: "present"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Centos Configure the Apache HTTP server
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "ServerName {{ openstack_vip_address }}"
    state: "present"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Centos Create a link to the /usr/share/keystone/wsgi-keystone.conf file
  command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
