- name: Create the keystone database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: keystone
    state: present

- name: Grant proper access to the keystone database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: keystone
    password: "{{ keystone_db_password }}"
    priv: "keystone.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"
