- name: Install keystone
  apt:
    name: "{{ item }}"
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi

- name: Prerequisites Database
  include: mysql.yml
  run_once: true

- name: Configure the Apache HTTP server
  include: config.yml

- name: Initialize Keystone
  include: keystone_initialize.yml

- name: Restart the Apache service
  service:
    name: apache2
    state: restarted
